# Generated by Django 5.0.1 on 2024-01-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='ser',
            new_name='user',
        ),
    ]
