# Generated by Django 5.0.1 on 2024-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0002_rename_revenue_budget_delete_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expense',
            field=models.BooleanField(default=False),
        ),
    ]
